# Site settings
theme: minima
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "TheSonicVerdict"
description: "Deep dives, hot takes, and sonic truth — a blog for music lovers."
baseurl: "" # Leave empty for GitHub Pages (username.github.io)
url: "https://justhal22.github.io/TheSonicVerdict" # Replace with your actual GitHub Pages URL
logo: "/assets/images/sonic-logo.png" # Put your logo in assets/images/
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200

mathjax:
  enable: false

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

google_analytics: "" # Optional
disqus:
  shortname: "thesonicverdict" # Set this up on Disqus if you want comments

twitter:
  username: "sonicverdict" # Or your real Twitter/X

# Liquid settings
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown

feed:
  path: atom.xml

# Pagination
paginate: 6
paginate_path: "/page:num/"

# Search
search_full_content: true

# Taxonomy (category/tag pages)
category_archive_path: "/categories/"
tag_archive_path: "/tags/"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Author details
author:
  name: "JustHal"
  picture: "/assets/images/author.png" # Optional author avatar
  email: "halbrookes22@gmail.com"
  twitter: "notavailable"
  links:
    - title: GitHub
      url: "https://github.com/justhal22"
      icon: fab fa-github
    - title: Twitter
      url: "https://twitter.com/sonicverdict"
      icon: fab fa-twitter
    - title: Email
      url: "mailto:halbrookes22@gmail.com"
      icon: fas fa-envelope

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: GitHub
    url: "https://github.com/justhal22/TheSonicVerdict"
    icon: fab fa-github
  - title: Twitter
    url: "https://twitter.com/sonicverdict"
    icon: fab fa-twitter
